ShoppingSite/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using ShoppingSite.Models;

namespace ShoppingSite.Controllers
{
	public class ItemController : BaseController
	{
		// TODO: gather the item info.

		public ActionResult Index(int? itemId)
		{
			var item = DB.Items.Find(itemId);

			if (item == null)
			{
				return new HttpNotFoundResult("The item cannot be found");
			}

			ViewData["categories"] = DB.Categories.ToList();

			return View(item);
		}
	}
}

ShoppingSite/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoppingSite.Models;

namespace ShoppingSite.Controllers
{
	public class SaleController : BaseController
	{
		public ActionResult Index(int? page)
		{
			page = page ?? 1;

			IEnumerable<Item> items = DB.Items.Where(i => i.Discount.HasValue);

			var itemsFiltered = items.OrderBy(i => i.Id).Skip((page.Value - 1) * Constants.NUM_ITEMS_PER_PAGE).Take(Constants.NUM_ITEMS_PER_PAGE);
			var totalPages = (items.Count() - 1) / Constants.NUM_ITEMS_PER_PAGE + 1;

			if (page > totalPages)
			{
				return HttpNotFound();
			}

			ViewBag.Page = page.Value;
			ViewBag.TotalPages = totalPages;

			return View(itemsFiltered);
		}
	}
}

ShoppingSite/Views/Sale/Index.cshtml
@using ShoppingSite.Models
@using ShoppingSite.Controllers
@model IEnumerable<Item>
@{
    ViewBag.Title = "Index";
    var items = Model;
    var currentPage = (int)ViewBag.Page;
    var query = ViewBag.Query as string;
    var totalPages = (int)ViewBag.TotalPages;
    var department = ViewBag.Department as Department;
    var departmentSearched = ViewBag.DepartmentSearched as String;
}
<div id="content">
    <aside class="white-box-top">
    </aside>
    <aside class="white-box-middle">
        <aside class="check-wrap">
            <aside class="clear">
                <span class="paging">
                    @for (int p = 1; p <= totalPages; p++)
                    {
                        if (p == currentPage)
                        {
                        <a href="@Url.Action("Index", "Sale", new { Query = query, Page = p, Department = departmentSearched })" class="activepage">@p</a>
                        }
                        else
                        {
                        <a href="@Url.Action("Index", "Sale", new { Query = query, Page = p, Department = departmentSearched })">@p</a>
                        }
                    }
                </span>
            </aside>
            <div class="clear">
            </div>
            <br />
            <br />
            <div class="clear">
                @{
                    var count = 0;
                }
                @foreach (var item in items)
                {
                    <aside class="pro-box" style="width: 144px;">
                        <a href="@Url.Action("Index", "Item", new { ItemId = item.Id })">
                            <img alt="" style="width:148px;" src="@Url.GetItemImageUrl(item)" />
                            <h1>@item.Name</h1>
                            @if (item.Discount.HasValue)
                            {
                                <h2>
                                    Price: <strong class="line-through"><span>&nbsp;@String.Format("{0:C}", item.Price)&nbsp; </span></strong>
                                </h2>
                                <aside class="discount">Discounted : <strong>@String.Format("{0:C}", item.Discount.Value)</strong></aside>
                            }
                            else
                            {
                                <h2>
                                    Price: <strong>@String.Format("{0:C}", item.Price)</strong>
                                </h2>
                            }
                        </a>
                    </aside>
                            if (++count % 5 == 0)
                            {
                    <div class="clear">
                        <br />
                        <br />
                    </div>
                            }
                }
            </div>
            <br />
            <br />
        </aside>
    </aside>
    <aside class="white-box-bottom">
    </aside>
    <div class="clear">
    </div>
</div>